version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      PASSENGER_APP_ENV: ${RAILS_ENV}
      DATABASE_URL: postgres://${FFCRM_DB_USERNAME}:${FFCRM_DB_PASSWORD}@db/${FFCRM_DB_PREFIX}_${RAILS_ENV}

  tasks:
    image: fat_free_crm_web:latest
    links:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV}
      PASSENGER_APP_ENV: ${RAILS_ENV}
      DATABASE_URL: postgres://${FFCRM_DB_USERNAME}:${FFCRM_DB_PASSWORD}@db/${FFCRM_DB_PREFIX}_${RAILS_ENV}
      USERNAME: ${FFCRM_ADMIN_USERNAME}
      PASSWORD: ${FFCRM_ADMIN_PASSWORD}
      EMAIL: ${FFCRM_ADMIN_EMAIL}

  db:
    image: postgres:9.6
    command: bash
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_PASSWORD: ${FFCRM_DB_PASSWORD}
      POSTGRES_USER: ${FFCRM_DB_USERNAME}
      POSTGRES_DB: ${FFCRM_DB_PREFIX}_${RAILS_ENV}

volumes:
  postgres_data: {}
